[project]
name = "neuron"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Lucas Rufkahr" }
]
requires-python = ">=3.14"
dependencies = [
    "matplotlib",
    "scipy",
    "numpy",
    "scipy-stubs",
]

[project.scripts]
neuron = "neuron:main"
neuron-projectile = "neuron.models.projectile:run"
neuron-pulse = "neuron.models.pulse:run"
neuron-rc = "neuron.models.rc:run"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.16.10",
    "ty>=0.0.84",
]
